### ISSUE TITLE
Add 'enable' variable to all child modules

### ISSUE THREAD

**Issue by jeheyer** [aws2gcp/gcp-network-terraform#1]
Each child module should have an `enable` variable or object attribute so resources can be easily enabled/disabled or re-created with minimal code changes at the parent module level.

**Comment by aws2gcp** [comment]
There should now be a `create` boolean in as a var and object attribute.  

https://www.reddit.com/r/Terraform/comments/13gvdez/standard_naming_scheme_for_kill_switch_variable/
