### ISSUE TITLE
 Error: Failed to find Service Networking Connection, err: Failed to retrieve network field value, err: project: required field is not set

### ISSUE THREAD

**Issue by jeheyer** [aws2gcp/gcp-network-terraform#2]
When bringing up service networking peering connection, fails with error:

**Error: Failed to find Service Networking Connection, err: Failed to retrieve network field value, err: project: required field is not set**

Example input:
```
ip_ranges = {
  servicenetworking = {
    name     = "servicenetworking"
    ip_range = "100.64.0.0/20"
  }
}
service_connections = {
  service-networking = {
    ip_ranges = ["servicenetworking"]
  }
}
```

**Comment by aws2gcp** [comment]
Looks like the `network` parameter of [google_service_networking_connection](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/service_networking_connection) should be the network ID (projects/my-project/global/networks/my-network), not just the name as the documentation states.

**Comment by aws2gcp** [comment]
https://github.com/aws2gcp/gcp-network-terraform/commit/785213f5bfe3319248f50043e879c8bc596cce83#diff-352904d3b353c3fac0d9245eb9a8fef3c2e6e45ab4ca327162cb89a7f99e5fd4
