### ISSUE TITLE
Add ability to give compute user access on subnets to specific accounts or groups

### ISSUE THREAD

**Issue by jeheyer** [aws2gcp/gcp-network-terraform#3]
The `attached_projects` attribute in the subnet variable gives compute.networkUser permissions to the services accounts for the service project.   It may also be required to give the same access to service accounts that operate cross-project.  A attribute like `shared_accounts` or something like that would be great!

**Comment by aws2gcp** [comment]
Done..and tested!   

https://github.com/aws2gcp/gcp-network-terraform/commit/6c6af5a51cba4b06434183bc1f7488c34734c4bc#diff-7a8f3d053ca4a6cd25afb934c570c0f095480be76a1cb9e95e2c67517f3bd9aa

**Comment by aws2gcp** [comment]
Done!

https://github.com/aws2gcp/gcp-network-terraform/commit/6c6af5a51cba4b06434183bc1f7488c34734c4bc#diff-7a8f3d053ca4a6cd25afb934c570c0f095480be76a1cb9e95e2c67517f3bd9aa
