### ISSUE TITLE
TF plan/apply error when passing newly created service account

### ISSUE THREAD

**Issue by jeheyer** [aws2gcp/gcp-network-terraform#4]
When calling MIG module with a new service account, get this error during plan/apply:

```
for_each = var.service_account_email != null ? { for i, v in local.ops_agent_roles : i => v } : {}
│     ├────────────────
│     │ local.ops_agent_roles is tuple with 2 elements
│     │ var.service_account_email is a string, known only after apply
```
As work around, run plan/apply with service account email commented out, then re-run plan/apply.  Or just use a pre-existing service account.

**Comment by aws2gcp** [comment]
Am able to reproduce.  Bit of a head-scratcher because this should just be passed by the SA e-mail value with an implicit depends_on, so not sure why it's complaining.

**Comment by aws2gcp** [comment]
Really looks like a Terraform bug.  Lots of conversations on this error message, none with a clear answer as it why it's being triggered.   Going to remove this from mig child module for now.

**Comment by jeheyer** [comment]
has been removed
