### ISSUE TITLE
Subnet-level permissions override network-level permissions in shared VPC

### ISSUE THREAD

**Issue by jeheyer** [aws2gcp/gcp-network-terraform#8]
When using the `shared_accounts` attribute for a subnet, it will override (potentially deleting) permissions at the network level for all subnets.

This may be intentional in a few cases, but in my case, then intent is for the subnets to inherit network permissions.

**Comment by aws2gcp** [comment]
```
      attached_projects    = concat(coalesce(v.attached_projects, []), coalesce(var.attached_projects, []))
      shared_accounts      = concat(coalesce(v.shared_accounts, []), coalesce(var.shared_accounts, []))
```
